### ISSUE TITLE
Line Errors in Project.yaml

### ISSUE THREAD

**Issue by CarolineMorton** [opensafely-core/job-runner#233]
I helped a researcher figure out an error with running their study locally. It turns out there was a stray colon that had erroneously been copied into a line mid-way through the project.yaml, which was >700 lines long. 

This was the error that the researcher sent me. 

```bash
Traceback (most recent call last):
  File "c:\users\qc18278\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\qc18278\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\qc18278\Anaconda3\Scripts\opensafely.exe\__main__.py", line 7, in <module>
  File "c:\users\qc18278\anaconda3\lib\site-packages\opensafely\__init__.py", line 61, in main
    success = function(**kwargs)
  File "c:\users\qc18278\anaconda3\lib\site-packages\opensafely\_vendor\jobrunner\local_run.py", line 145, in main
    success_flag = create_and_run_jobs(
  File "c:\users\qc18278\anaconda3\lib\site-packages\opensafely\_vendor\jobrunner\local_run.py", line 230, in create_and_run_jobs
    create_jobs(job_request)
  File "c:\users\qc18278\anaconda3\lib\site-packages\opensafely\_vendor\jobrunner\create_or_update_jobs.py", line 109, in create_jobs
    return create_jobs_with_project_file(job_request, project_file)
  File "c:\users\qc18278\anaconda3\lib\site-packages\opensafely\_vendor\jobrunner\create_or_update_jobs.py", line 113, in create_jobs_with_project_file
    project = parse_and_validate_project_file(project_file)
  File "c:\users\qc18278\anaconda3\lib\site-packages\opensafely\_vendor\jobrunner\project.py", line 68, in parse_and_validate_project_file
    project = validate_project_and_set_defaults(project)
  File "c:\users\qc18278\anaconda3\lib\site-packages\opensafely\_vendor\jobrunner\project.py", line 174, in validate_project_and_set_defaults
    if dependency not in project_actions:
TypeError: unhashable type: 'dict'
``` 

It would be possible to surface the line where the error is occurring - in this case, the stray colon causing a TypeError. I had to manually do this by commenting in and out blocks to gradually narrow it down.

**Comment by sebbacon** [comment]
@bloodearnest is this adjacent to the background-bonus work you mentioned?

**Comment by bloodearnest** [comment]
Yes.
