### ISSUE TITLE
Issue with running cohort-joiner

### ISSUE THREAD

**Issue by rose-higgins** [opensafely-core/job-runner#457]
An action using the cohort-joiner reusable action has stopped working in 2 of my repos ([here](https://github.com/opensafely/asthma_sro/tree/panelled_plots) and [here](https://github.com/opensafely/asthma_indicators_qof/tree/planel_plots)). The error I am getting is below
```
Traceback (most recent call last):
  File "C:\Users\higginsr\anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\higginsr\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\higginsr\anaconda3\Scripts\opensafely.exe\__main__.py", line 7, in <module>
  File "C:\Users\higginsr\anaconda3\lib\site-packages\opensafely\__init__.py", line 79, in main
    success = function(**kwargs)
  File "C:\Users\higginsr\anaconda3\lib\site-packages\opensafely\_vendor\jobrunner\cli\local_run.py", line 155, in main
    success_flag = create_and_run_jobs(
  File "C:\Users\higginsr\anaconda3\lib\site-packages\opensafely\_vendor\jobrunner\cli\local_run.py", line 253, in create_and_run_jobs
    job_request, jobs = create_job_request_and_jobs(
  File "C:\Users\higginsr\anaconda3\lib\site-packages\opensafely\_vendor\jobrunner\cli\local_run.py", line 442, in create_job_request_and_jobs
    resolve_reusable_action_references(new_jobs)
  File "C:\Users\higginsr\anaconda3\lib\site-packages\opensafely\_vendor\jobrunner\reusable_actions.py", line 50, in resolve_reusable_action_references
    run_command, repo_url, commit = handle_reusable_action(job.run_command)
  File "C:\Users\higginsr\anaconda3\lib\site-packages\opensafely\_vendor\jobrunner\reusable_actions.py", line 85, in handle_reusable_action
    reusable_action = fetch_reusable_action(image, tag)
  File "C:\Users\higginsr\anaconda3\lib\site-packages\opensafely\_vendor\jobrunner\reusable_actions.py", line 146, in fetch_reusable_action
    action_file = git.read_file_from_repo(repo_url, commit, "action.yaml")
  File "C:\Users\higginsr\anaconda3\lib\site-packages\opensafely\_vendor\jobrunner\lib\git.py", line 53, in read_file_from_repo
    ensure_commit_fetched(repo_dir, repo_url, commit_sha)
  File "C:\Users\higginsr\anaconda3\lib\site-packages\opensafely\_vendor\jobrunner\lib\git.py", line 193, in ensure_commit_fetched
    if not commit_already_fetched(repo_dir, commit_sha):
  File "C:\Users\higginsr\anaconda3\lib\site-packages\opensafely\_vendor\jobrunner\lib\git.py", line 216, in commit_already_fetched
    response = subprocess_run(
  File "C:\Users\higginsr\anaconda3\lib\site-packages\opensafely\_vendor\jobrunner\lib\subprocess_utils.py", line 19, in subprocess_run
    return subprocess.run(cmd_args, **kwargs)
  File "C:\Users\higginsr\anaconda3\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'tag', '--list', 'fetched/da032073105a29470dc969a90e8e637d58d634e8', '--points-at', 'da032073105a29470dc969a90e8e637d58d634e8', '--format', 'exists']' returned non-zero exit status 128.

stderr:

fatal: not a git repository (or any of the parent directories): .git
```

**Comment by iaindillingham** [comment]
Thanks for reporting this, @rose-higgins. This is similar to, but not the same as, opensafely-core/opensafely-cli#80. We can debug this some more tomorrow. However, I think we should take a look at where the OpenSAFELY CLI is storing reusable actions, which is a sub-directory of the system's temporary directory. We can find this with:

```sh
python -c 'import tempfile; print(tempfile.gettempdir())'
```

Let's use Git Bash to explore further, where `<tempdir>` is the value displayed by the above command. Run:

```sh
ls <tempdir>
```

You should see a directory in the list called `opensafely_<user>` where `<user>` is either your login name on the system, or `unknown`. Run:

```sh
ls <tempdir>/opensafely_<user>
```

I'd like to know what you see 🙂.

---

Note to self: Is `jobrunner.lib.git.get_local_repo_dir` working correctly? Rose is using a Windows system and executing `opensafely` using the [command prompt](https://en.wikipedia.org/wiki/Cmd.exe). It calls `jobrunner.lib.string_utils.project_name_from_url`:

https://github.com/opensafely-core/job-runner/blob/a121256d664ca0a582fbaeb1b7c820df4cade1e9/jobrunner/lib/string_utils.py#L13-L26

We'd expect `project_name_from_url("https://github.com/opensafely-actions/cohort-joiner")` to return `cohort-joiner`.

**Comment by rose-higgins** [comment]
Just logging here - after running the bits I got 
_cohort-joiner.git/  dataset-report.git/  deciles-charts.git/_

**Comment by iaindillingham** [comment]
@rose-higgins reports that she has rerun both repos successfully this morning. We've taken a look inside job-runner's temporary directory and can see that the subdirectory for cohort-joiner was created today (24th August). However, the subdirectory for dataset-report was created two days' ago (22nd August), so the system hasn't deleted job-runner's temporary directory and solved the problem for us.

I'm unsure why this errored yesterday but didn't error today. I think the best solution would be to log job-runner's local run mode. I'm going to close this issue and open a second issue for logging.
