### ISSUE TITLE
Internal error - requested actions already scheduled

### ISSUE THREAD

**Issue by rebkwok** [opensafely-core/job-runner#637]
Internal error on job-runner reported by [honeycomb](https://ui.honeycomb.io/bennett-institute-for-applied-data-science/environments/production/datasets/jobrunner/result/GQbw27GDEXX/a/5VeGQBghYn8)

Job:
https://jobs.opensafely.org/the-effect-of-long-covid-on-quality-adjusted-life-years-using-openprompt/openprompt-hrqol/20051/

The traceback is:
```
Traceback (most recent call last):
  File "/srv/jobrunner/code/jobrunner/create_or_update_jobs.py", line 55, in create_or_update_jobs
    new_job_count = create_jobs(job_request)
  File "/srv/jobrunner/code/jobrunner/create_or_update_jobs.py", line 91, in create_jobs
    assert_new_jobs_created(job_request, new_jobs, latest_jobs)
  File "/srv/jobrunner/code/jobrunner/create_or_update_jobs.py", line 301, in assert_new_jobs_created
    raise JobRequestError("All requested actions were already scheduled to run")
jobrunner.create_or_update_jobs.JobRequestError: All requested actions were already scheduled to run
```

**Comment by madwort** [comment]
I believe this is fixed by https://github.com/opensafely-core/job-runner/pull/648
