### ISSUE TITLE
Database is locked error

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/job-runner#664]
A recent job produced an internal error that seems to be related to the SQLite database used by job runner (I could be reading the stack trace incorrectly, but I think it errored when trying to update the job).

[Honeycomb details](https://ui.honeycomb.io/bennett-institute-for-applied-data-science/environments/production/datasets/jobrunner/trace/y95AAmE4cHo?fields[]=c_name&fields[]=c_service.name&span=fbfa363a8467981d)

[Job details](https://jobs.opensafely.org/the-impact-of-covid-19-on-pregnancy-treatment-pathways-and-outcomes/main_pregnancy_tx_pathways/20644/e6yzuqia5jjjjajh/) in Job Server

```
Traceback (most recent call last):
  File "/home/opensafely/jobrunner/code/jobrunner/run.py", line 153, in handle_single_job
    synchronous_transition = trace_handle_job(job, api, mode, paused)
  File "/home/opensafely/jobrunner/code/jobrunner/run.py", line 190, in trace_handle_job
    synchronous_transition = handle_job(job, api, mode, paused)
  File "/home/opensafely/jobrunner/code/jobrunner/run.py", line 298, in handle_job
    set_code(job, code, message)
  File "/home/opensafely/jobrunner/code/jobrunner/run.py", line 668, in set_code
    update_job(job)
  File "/home/opensafely/jobrunner/code/jobrunner/run.py", line 741, in update_job
    update(job, exclude_fields=["cancelled"])
  File "/home/opensafely/jobrunner/code/jobrunner/lib/database.py", line 80, in update
    update_where(item.__class__, update_dict, id=item.id)
  File "/home/opensafely/jobrunner/code/jobrunner/lib/database.py", line 90, in update_where
    get_connection().execute(
sqlite3.OperationalError: database is locked
```

**Comment by lucyb** [comment]
This was almost certainly due to some work that Simon was doing on the server and doesn't need any further investigation.
